services:
  shipment-db:
    extends:
      file: docker-compose-base.yaml
      service: shipment-db
    ports:
      - 5432:5432
  shipment:
    extends:
      file: docker-compose-base.yaml
      service: shipment
    ports:
      - 8080:8080
  shipment-dapr:
    extends:
      file: docker-compose-base.yaml
      service: shipment-dapr
    volumes:
      - "./.dapr/dapr-config-minimal.yaml:/config.yaml"
      - "./.dapr/components:/components"
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
volumes:
  shipment-db-data: