services:
  shipment-db:
    extends:
      file: docker-compose-base.yaml
      service: shipment-db
    ports:
      - 5432:5432
  shipment:
    extends:
      file: docker-compose-base.yaml
      service: shipment
    ports:
      - 8080:8080
    environment:
      - MISARCH_SHIPMENT_PROVIDER_ENDPOINT=http://debug-shipment-provider:8080
  shipment-dapr:
    extends:
      file: docker-compose-base.yaml
      service: shipment-dapr
    volumes:
      - "./.dapr/dapr-config-minimal.yaml:/config.yaml"
      - "./.dapr/components:/components"
  debug-shipment-provider:
    image: "mendhak/http-https-echo:31"
    environment:
      - ECHO_BACK_TO_CLIENT=false
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
volumes:
  shipment-db-data: