spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://shipment-db:5432/shipment
  flyway:
    url: jdbc:postgresql://shipment-db:5432/shipment
    locations: classpath:db/migration
graphql:
  packages: org.misarch.shipment
  federation:
    enabled: true